[tool.mypy]
python_version = "3.12"
disable_error_code = "name-defined,arg-type,attr-defined,import-untyped,name-match,assignment,import-not-found"
exclude = ["imports/hans_old/"]


[tool.pyright]
exclude = ["**/hans_old", ".mypy_cache", ".venv"]

pythonVersion = "3.12"

# Temporarily disabled (WIP)

reportArgumentType = "none"
reportAttributeAccessIssue = "none"
reportCallIssue = "none"
reportFunctionMemberAccess = "none"
reportGeneralTypeIssues = "none"
reportIncompatibleMethodOverride = "none"
reportIndexIssue = "none"
reportInvalidTypeArguments = "none"
reportMissingImports = "none"
reportOperatorIssue = "none"
reportOptionalIterable = "none"
reportOptionalMemberAccess = "none"
reportOptionalOperand = "none"
reportOptionalSubscript = "none"
reportPossiblyUnboundVariable = "none"
reportReturnType = "none"
reportSelfClsParameterName = "none"
reportUndefinedVariable = "none"
