[tool.pyright]
exclude = ["**/hans_old", ".mypy_cache", ".venv", "parliament/politicians/twit.py"]

pythonVersion = "3.12"

typeCheckingMode = "strict"

reportArgumentType = "none"
reportAttributeAccessIssue = "none"
reportOptionalMemberAccess = "none"

reportUnknownVariableType = "none"
reportUnknownMemberType = "none"
reportMissingTypeArgument = "none"
reportUnknownArgumentType = "none"
reportUnknownParameterType = "none"
reportMissingParameterType = "none"
reportMissingTypeStubs = "none"
reportPrivateUsage = "none"
reportUnknownLambdaType = "none"
reportUntypedBaseClass = "none"
