[tool.mypy]
python_version = "3.12"
disable_error_code = "name-defined,attr-defined,import-untyped,arg-type,index,union-attr,assignment,misc,override,call-overload"
exclude = ["imports/hans_old/"]
check_untyped_defs = true


[tool.pyright]
exclude = ["**/hans_old", ".mypy_cache", ".venv", "parliament/politicians/twit.py"]

pythonVersion = "3.12"

# TODO make strict
typeCheckingMode = "basic"

reportArgumentType = "none"
reportAttributeAccessIssue = "none"
reportCallIssue = "none"
reportIndexIssue = "none"
reportOptionalMemberAccess = "none"
